import type {
  Finding,
  Recommendation,
  Report,
  RiskLevel,
  Severity,
} from "./schema.js";

export const REPORT_MARKER = "<!-- pullstack-report -->";

const SEVERITY_RANK: Record<Severity, number> = {
  critical: 4,
  high: 3,
  medium: 2,
  low: 1,
  info: 0,
};

function titleCase(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function levelLabel(level: RiskLevel): string {
  return titleCase(level);
}

function recommendationLabel(rec: Recommendation): string {
  switch (rec) {
    case "safe_to_merge":
      return "✅ Safe to merge";
    case "needs_review":
      return "🟡 Needs review";
    case "blocked":
      return "⛔ Blocked";
  }
}

function riskEmoji(level: RiskLevel): string {
  switch (level) {
    case "low":
      return "🟢";
    case "medium":
      return "🟡";
    case "high":
      return "🟠";
    case "critical":
      return "🔴";
  }
}

function escapePipes(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function findingsTable(findings: Finding[]): string {
  // Hide pure-noise info findings from the headline table, but keep ownership.
  const visible = findings
    .filter((f) => f.severity !== "info" || f.category === "ownership")
    .slice()
    .sort((a, b) => SEVERITY_RANK[b.severity] - SEVERITY_RANK[a.severity]);

  if (visible.length === 0) return "_No findings._";

  const rows = visible
    .map(
      (f) =>
        `| ${titleCase(f.severity)} | ${f.category} | ${escapePipes(f.message)} |`,
    )
    .join("\n");
  return `| Severity | Category | Finding |\n|---|---|---|\n${rows}`;
}

export function renderMarkdown(report: Report): string {
  const lines: string[] = [];

  lines.push(REPORT_MARKER);
  lines.push("");
  lines.push("## PullStack PR Risk Report");
  lines.push("");
  lines.push(
    `**Risk:** ${riskEmoji(report.risk.level)} ${levelLabel(report.risk.level)}, ${report.risk.score} / 100  `,
  );
  lines.push(`**Merge recommendation:** ${recommendationLabel(report.mergeRecommendation)}  `);
  lines.push(
    `**Changed:** ${report.stats.changedFiles} files (+${report.stats.added}/-${report.stats.deleted})  `,
  );
  lines.push(`**Base:** \`${report.base}\` → **Head:** \`${report.head}\``);
  lines.push("");

  lines.push("### Summary");
  lines.push(report.summary);
  lines.push("");

  lines.push("### Key Findings");
  lines.push(findingsTable(report.findings));
  lines.push("");

  if (report.reviewFocus.length > 0) {
    lines.push("### Review Focus");
    report.reviewFocus.forEach((rf, i) => {
      lines.push(`${i + 1}. \`${rf.file}\` — ${rf.reason}`);
    });
    lines.push("");
  }

  if (report.suggestedReviewers.length > 0) {
    lines.push("### Suggested Reviewers");
    for (const r of report.suggestedReviewers) {
      lines.push(`- ${r}`);
    }
    lines.push("");
  }

  if (report.overlap.length > 0) {
    lines.push("### PR Overlap");
    for (const o of report.overlap) {
      const link = o.url ? `[#${o.number}](${o.url})` : `#${o.number}`;
      lines.push(`- PR ${link} overlaps on ${o.overlappingFiles.map((f) => `\`${f}\``).join(", ")}`);
    }
    lines.push("");
  }

  if (
    report.semantic.status === "ok" &&
    report.semantic.splitRecommended &&
    report.semantic.splitReason
  ) {
    lines.push("### Suggested Split");
    lines.push(report.semantic.splitReason);
    lines.push("");
  }

  lines.push("### Suggested Next Steps");
  for (const step of report.nextSteps) {
    lines.push(`- ${step}`);
  }
  lines.push("");

  // Footer with provenance / semantic status.
  const semanticNote =
    report.semantic.status === "ok"
      ? "semantic analysis merged"
      : report.semantic.status === "invalid"
        ? "semantic analysis present but invalid"
        : "deterministic only (no semantic analysis)";
  lines.push("---");
  lines.push(
    `<sub>Generated by PullStack (${semanticNote}) at ${report.generatedAt}.</sub>`,
  );

  return lines.join("\n");
}
